
// Path: /Users/ozan/projects/fullstack-starter/kit2/client/pages.gen.ts

// Auto-generated by watch-pages.ts

declare global { type ClientRoutePath = "/login" | "/change-password" | "/root" | "/register" | "/profile" | "/forgot-password" | "/verify-email"; type ExtractRouteParams<T> = T extends `${infer _Start}:${infer Param}/${infer Rest}`
 ? { [k in Param | keyof ExtractRouteParams<Rest>]: string } : T extends `${infer _Start}:${infer Param}` ? { [k in Param]: string } : { [k in string]: string }; type ExtractSearchParams<P> = P extends `${infer _Start}?${infer Search}` ? { [k in Search]: string } : { [k in string]: string }; type ClientRoutePathParam<P extends ClientRoutePath> = ExtractRouteParams<P>; type ClientRouteSearchParam<P extends ClientRoutePath> = ExtractSearchParams<P>; }

export const RoutesMap = {"Login":{"path":"/login","name":"Login"},"ChangePassword":{"path":"/change-password","name":"ChangePassword"},"Root":{"path":"/root","name":"Root"},"Register":{"path":"/register","name":"Register"},"Profile":{"path":"/profile","name":"Profile"},"ForgotPassword":{"path":"/forgot-password","name":"ForgotPassword"},"VerifyEmail":{"path":"/verify-email","name":"VerifyEmail"}};

export const pagePaths:ClientRoutePath[] = ["/login","/change-password","/root","/register","/profile","/forgot-password","/verify-email"];
