
// Auto-generated by watch-routes.ts


type ExtractRouteParams<T> = T extends `${infer _Start}:${infer Param}/${infer Rest}`
 ? { [k in Param | keyof ExtractRouteParams<Rest>]: string } : T extends `${infer _Start}:${infer Param}` ? { [k in Param]: string } : { [k in string]: string };
type ExtractSearchParams<P> = P extends `${infer _Start}?${infer Search}` ? { [k in Search]: string } : { [k in string]: string };

declare global { type ClientRoutePath = "/forgot-password" | "/login" | "/verify-email" | "/" | "/profile" | "/change-password" | "/register"; type ClientRoutePathParam<P extends ClientRoutePath> = ExtractRouteParams<P>; type ClientRouteSearchParam<P extends ClientRoutePath> = ExtractSearchParams<P>; }

export const clientRoutesMap = [{"name":"ForgotPassword","path":"/forgot-password"},{"name":"Login","path":"/login"},{"name":"VerifyEmail","path":"/verify-email"},{"name":"Root","path":"/"},{"name":"Profile","path":"/profile"},{"name":"ChangePassword","path":"/change-password"},{"name":"Register","path":"/register"}];

export const clientRoutePaths:ClientRoutePath[] = ["/forgot-password","/login","/verify-email","/","/profile","/change-password","/register"];


declare global { type ServerRoutePath = "/api/auth/verify-email" | "/api/auth/profile" | "/api/auth/change-password" | "/api/auth/register" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/verify-email-resend"; type ServerRoutePathParam<P extends ServerRoutePath> = ExtractRouteParams<P>; type ServerRouteSearchParam<P extends ServerRoutePath> = ExtractSearchParams<P>; }

export const serverRoutesMap = [{"name":"ApiAuthVerifyEmailPost","path":"/api/auth/verify-email","method":"POST"},{"name":"ApiAuthProfileGet","path":"/api/auth/profile","method":"GET"},{"name":"ApiAuthChangePasswordPost","path":"/api/auth/change-password","method":"POST"},{"name":"ApiAuthRegisterPost","path":"/api/auth/register","method":"POST"},{"name":"ApiAuthForgotPasswordPost","path":"/api/auth/forgot-password","method":"POST"},{"name":"ApiAuthLoginPost","path":"/api/auth/login","method":"POST"},{"name":"ApiAuthLogoutPost","path":"/api/auth/logout","method":"POST"},{"name":"ApiAuthVerifyEmailResendPost","path":"/api/auth/verify-email-resend","method":"POST"}];

export const serverRoutePaths:ServerRoutePath[] = ["/api/auth/verify-email","/api/auth/profile","/api/auth/change-password","/api/auth/register","/api/auth/forgot-password","/api/auth/login","/api/auth/logout","/api/auth/verify-email-resend"];


	