
// Path: /Users/ozan/projects/fullstack-starter/kit/client/src/config.ts

// Auto-generated by watch-pages.ts

declare global { type ClientRoutePath = "/profile" | "/login" | "/" | "/change-password" | "/forgot-password" | "/register" | "/verify-email"; type ExtractRouteParams<T> = T extends `${infer _Start}:${infer Param}/${infer Rest}`
 ? { [k in Param | keyof ExtractRouteParams<Rest>]: string } : T extends `${infer _Start}:${infer Param}` ? { [k in Param]: string } : { [k in string]: string }; type ExtractSearchParams<P> = P extends `${infer _Start}?${infer Search}` ? { [k in Search]: string } : { [k in string]: string }; type ClientRoutePathParam<P extends ClientRoutePath> = ExtractRouteParams<P>; type ClientRouteSearchParam<P extends ClientRoutePath> = ExtractSearchParams<P>; }

export const RoutesMap = {"Profile":{"path":"/profile","name":"Profile"},"Login":{"path":"/login","name":"Login"},"Root":{"path":"/","name":"Root"},"ChangePassword":{"path":"/change-password","name":"ChangePassword"},"ForgotPassword":{"path":"/forgot-password","name":"ForgotPassword"},"Register":{"path":"/register","name":"Register"},"VerifyEmail":{"path":"/verify-email","name":"VerifyEmail"}};

export const pagePaths:ClientRoutePath[] = ["/profile","/login","/","/change-password","/forgot-password","/register","/verify-email"];
